# replace token with result from auth login below
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJlbWFpbCI6InN1cGVyYWRtaW5AZ21haWwuY29tIn0sImlhdCI6MTczNDQyMTQwMCwiZXhwIjoxNzM0NDIyNjAwfQ.bxsxGL_6ATh4cDZGNbrNFm5AbuudC4gCL273kpKq9xI

###
# auth login to get access token
POST http://localhost:5000/auth 
Content-Type: application/json

{
    "email":"superadmin@gmail.com",
    "password":"superadmin"
}

###
GET http://localhost:5000

###
# get list of contacts
GET http://localhost:5000/contact?limit=10&offset=0
Authorization: Bearer {{token}}

###
# add new contact
POST http://localhost:5000/contact
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name":"Medina",
    "email":"medina@gmail.com",
    "phone":"9888399333"
}

###
# delete existing contact by its id
DELETE http://localhost:5000/contact/1

###
# update contact by its id
PUT http://localhost:5000/contact/2
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name":"Kataky Smile",
    "email":"kataky@gmail.com",
    "phone":"9888399333"
}