POST http://localhost:5000/auth 
Content-Type: application/json

{
    "email":"superadmin@gmail.com",
    "password":"superadmin"
}

###
GET http://localhost:5000

###
GET http://localhost:5000/contact?limit=10&offset=0

###
POST http://localhost:5000/contact
Content-Type: application/json

{
    "name":"Medina",
    "email":"medina@gmail.com",
    "phone":"9888399333"
}

###
DELETE http://localhost:5000/contact/1

###
PUT http://localhost:5000/contact/2
Content-Type: application/json

{
    "name":"Kataky Smile",
    "email":"kataky@gmail.com",
    "phone":"9888399333"
}